name: Test Docker Image

on: [pull_request]

jobs:
  build-test:
    uses: iExecBlockchainComputing/github-actions-workflows/.github/workflows/docker-build.yml@feat/docker-build/enhance-reporting
    with:
      image-name: 'iexechub/voucher-subgraph-deployer'
      image-tag: ${{ github.sha }}
      push: false
      security-scan: true
      security-report: "comment"
